name: Generate Blogger Sitemap

on:
  schedule:
    - cron: '0 3 * * *'  # 每天运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser

      - name: Generate sitemap.xml
        run: python generate.py


      - name: Commit and push sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap.xml || true
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update sitemap"
          git push

          
